baseurl = "http://www.example.com"
title = "Profile"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Sai Navaneet"
  info = "Here, you can check out what I'm working on. I try my best to create things with ❤"
  description = "Navaneet personal website"
  keywords = "Researcher, Engineer ,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "sainavaneet76@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/sainavaneet/"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa-brands fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/johndoe/"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa-brands fa-x-twitter fa-2x"
#   weight = 3
#   url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
